[package]
name = "rs_flow"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
rs_coroutine_core = { path = "../rs_coroutine_core" }
tokio = { version = "1", features = ["sync", "macros", "rt", "rt-multi-thread", "time"] }
