[package]
name = "rs_coroutine_core"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
once_cell = "1"
rs_coroutine_macros = { path = "../rs_coroutine_macros" }
tokio = { version = "1", features = ["sync", "macros", "rt", "rt-multi-thread", "time"] }
